FROM ironmansoftware/universal:4.1.8-ubuntu-20.04
LABEL description="PS Universal Configured for Persistent Storage" 

EXPOSE 5000
VOLUME ["/home/data"]
ENV Data__RepositoryPath /home/data/Repository
ENV Data__ConnectionString /home/data/database.db
ENV UniversalDashboard__AssetsFolder /home/data/UniversalDashboard 
ENV Logging__Path /home/data/logs/log.txt
RUN apt-get install -y tzdata
ENTRYPOINT ["./Universal/Universal.Server"]
